on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: workspace-cache
        with:
          path: ~/.workspace
          key: ubuntu-latest-workspace

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: install modules
        run: |
          pip install -U pip
          pip install -U wheel
      - name: show versions
        run: |
          g++ --version
          python --version
      - name: run test
        run: |
          python ./setup.py -q test
